set -e
true
true
/media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/bin/spades-hammer /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/corrected/configs/config.info
/media/ubuntu/conda/anaconda3/envs/vambnew/bin/python /media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/compress_all.py --input_file /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/corrected/corrected.yaml --ext_python_modules_home /media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/share/spades --max_threads 66 --output_dir /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/corrected --gzip_output
true
true
/media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/bin/spades-core /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K21/configs/config.info /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K21/configs/mda_mode.info /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K21/configs/meta_mode.info
/media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/bin/spades-core /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K33/configs/config.info /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K33/configs/mda_mode.info /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K33/configs/meta_mode.info
/media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/bin/spades-core /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/configs/config.info /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/configs/mda_mode.info /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/configs/meta_mode.info
/media/ubuntu/conda/anaconda3/envs/vambnew/bin/python /media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/copy_files.py /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/before_rr.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/before_rr.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/assembly_graph_after_simplification.gfa /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/assembly_graph_after_simplification.gfa /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/final_contigs.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/contigs.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/first_pe_contigs.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/first_pe_contigs.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/strain_graph.gfa /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/strain_graph.gfa /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/scaffolds.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/scaffolds.fasta /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/scaffolds.paths /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/scaffolds.paths /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/assembly_graph_with_scaffolds.gfa /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/assembly_graph_with_scaffolds.gfa /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/assembly_graph.fastg /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/assembly_graph.fastg /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/K55/final_contigs.paths /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/contigs.paths
true
/media/ubuntu/conda/anaconda3/envs/vambnew/bin/python /media/ubuntu/abc/lzh/soft/SPAdes-3.15.4-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/scaffolds.fasta --misc_dir /media/ubuntu/abc/csm/DCVBin_project/test/assembly_out/misc --threshold_for_breaking_scaffolds 3
true
