set -e
true
true
/fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/bin/spades-hammer /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/corrected/configs/config.info
/home/wangjingyuan/anaconda3/envs/vambnew/bin/python3 /fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/corrected/corrected.yaml --ext_python_modules_home /fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/share/spades --max_threads 66 --output_dir /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/corrected --gzip_output
true
true
/fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/bin/spades-core /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K21/configs/config.info /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K21/configs/mda_mode.info /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K21/configs/meta_mode.info
/fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/bin/spades-core /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K33/configs/config.info /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K33/configs/mda_mode.info /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K33/configs/meta_mode.info
/fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/bin/spades-core /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/configs/config.info /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/configs/mda_mode.info /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/configs/meta_mode.info
/home/wangjingyuan/anaconda3/envs/vambnew/bin/python3 /fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/share/spades/spades_pipeline/scripts/copy_files.py /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/before_rr.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/before_rr.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/assembly_graph_after_simplification.gfa /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/assembly_graph_after_simplification.gfa /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/final_contigs.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/contigs.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/first_pe_contigs.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/first_pe_contigs.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/strain_graph.gfa /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/strain_graph.gfa /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/scaffolds.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/scaffolds.fasta /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/scaffolds.paths /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/scaffolds.paths /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/assembly_graph_with_scaffolds.gfa /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/assembly_graph_with_scaffolds.gfa /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/assembly_graph.fastg /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/assembly_graph.fastg /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/K55/final_contigs.paths /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/contigs.paths
true
/home/wangjingyuan/anaconda3/envs/vambnew/bin/python3 /fs1/private/user/wangjingyuan/anaconda3/envs/vambnew/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/scaffolds.fasta --misc_dir /home/wangjingyuan/lyf/DCVBin_project/test_zuixin/assembly_out/misc --threshold_for_breaking_scaffolds 3
true
